### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by torsday** [benogle/github-url-resolver#1]
[Enter steps to reproduce below:]
1. highlight a list of username/repos
2. try to resolve, fail.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [github-url-resolver](https://github.com/benogle/github-url-resolver) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Users/chris.torstenson/.atom/packages/github-url-resolver/lib/url-resolver.coffee:47

TypeError: Cannot read property 'length' of null
    at Object.module.exports.extractURLs (/Users/chris.torstenson/.atom/packages/github-url-resolver/lib/url-resolver.coffee:47:5)
    at Object.module.exports.resolveURLsInString (/Users/chris.torstenson/.atom/packages/github-url-resolver/lib/url-resolver.coffee:17:13)
    at Object.module.exports.GithubURLResolver.resolveURLs (/Users/chris.torstenson/.atom/packages/github-url-resolver/lib/github-url-resolver.coffee:22:34)
    at atom-text-editor.subscriptions.add.atom.commands.add.github-url-resolver:resolve-urls (/Users/chris.torstenson/.atom/packages/github-url-resolver/lib/github-url-resolver.coffee:12:102)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:36.6.0 editor:select-line (atom-text-editor.editor.is-focused)
     -2:35.7.0 editor:split-selections-into-lines (atom-text-editor.editor.is-focused)
     -2:35.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:32.6.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -2:22.5.0 markdown-writer:indent-list-line (atom-text-editor.editor.is-focused)
     -2:22.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:22.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:22.5.0 markdown:indent-list-item (atom-text-editor.editor.is-focused)
     -2:18.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:03.8.0 core:copy (div.markdown-preview.native-key-bindings)
     -0:58 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:44.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14 core:close (div.panels)
     -0:10.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.3.0 github-url-resolver:resolve-urls (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "indent-guide-improved",
      "auto-detect-indentation",
      "emmet",
      "atom-autocomplete-php",
      "jshint",
      "atom-alignment",
      "atom-ctags",
      "minimap",
      "linter-raml",
      "merge-conflicts",
      "pigments",
      "minimap-highlight-selected",
      "metrics",
      "symbols-view",
      "symbol-gen",
      "atom-terminal",
      "highlight-selected",
      "minimap-git-diff",
      "api-workbench",
      "vim-mode",
      "color-picker",
      "vim-surround",
      "vim-mode-clipboard-plus",
      "language-gfm",
      "clipboard-plus"
    ],
    "ignoredNames": [
      "public"
    ],
    "packagesWithKeymapsDisabled": [
      "php-cs-fixer"
    ],
    "themes": [
      "atom-material-ui",
      "pacific-dark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.14.2
aligner, v0.19.1
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
atom-beautify, v0.28.22
atom-material-ui, v1.2.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
docblockr, v0.7.3
editorconfig, v1.2.4
file-icons, v1.6.15
gist-it, v0.9.0
git-plus, v5.13.0
github-url-resolver, v0.1.0
highlight-line, v0.11.1
language-javascript-jsx, v0.3.7
language-markdown, v0.11.0
language-swift, v0.4.0
linter, v1.11.3
linter-eslint, v7.0.0
markdown-scroll-sync, v2.1.2
markdown-toc, v0.4.1
markdown-writer, v2.3.1
pacific-dark, v0.4.0
php-cs-fixer, v2.5.6
php-debug, v0.2.2
php-hyperclick, v0.3.1
pretty-json, v0.4.1
raml, v0.2.0
react, v0.14.1
set-syntax, v0.3.0
sort-lines, v0.14.0
synced-sidebar, v0.4.3
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Thanks for the report!
